### ISSUE TITLE
Alternative MST-Parsing

### ISSUE THREAD

**Issue by akolonin** [singnet/language-learning#106]
Ben wrote:
Suppose we train an RNN Probability Estimator on our corpus, such as described in

https://web.stanford.edu/class/cs224n/reports/2761006.pdf

This is a RNN that estimates

P( W(n+1) = w | W(1), …, W(n) )

where W(n) is the n’th word in the corpus and w is some particular word…

If we want to assign a weight to the dependency link going left-to-right between word v and word w … we could look at

A = average of P( W(n+1) = w | W(1), …, W(n) ) over all cases where W(n+1)=w is actually true

B = average of P( W(n+1) = w | W(1), …, W(n) ) over all cases where W(n+1)=w is actually true, and v occurs before w in the same sentence

Then, d = B - A is one measure of how much extra information about occurrence of w is given via the knowledge that v occurs in the sentence

(One can make a similar measure going backwards in the sentence, by making an RNN that analyzes the corpus backwards, and then estimating the same quantity that way.)

This is an alternative to looking at the mutual information between v and w, which may be better in the sense that it incorporates a lot of higher-order dependencies based on context…

My suggestion is that the cost of the link between v and w in a candidate MST parse could be assigned based on this d value rather than based on mutual information…

There is likely some nicer way to work the math, but I hope the idea is clear…

Also — If one already has parses of the sentences in the corpus, the links in these parses can be included as extra features input to the RNN that  makes the predictions.

This also suggests that compression could be useful as a metric of a grammar learned by ULL.   If creating a probability model using parses as additional features, results in a more accurate probability model, then for a large corpus this will yield greater compression than one would get by not using the parses as additional features.   The amount of compression obtained is a measure of the quality of the grammar learned.

**Comment by akolonin** [comment]
This makes sense. I think once @alexei-gl finishes integration of OpenCog MST-Parser in pipeline it maybe the first thing to try to get alternative MST-Parses. We have different ways to assess real quality of MST parses now - parse accuracy and overall learned grammar PQ/F1

**Comment by akolonin** [comment]
One simple possibility to have it done is just load pre-parsed (per #188) cleaned corpus file as well as *.fmi file exported by MI-Observer and output *.ull file with all links with FMI exceeding the configured threshold. For *.ull file produced by DNN-MI-Milking, no special parsing is required at all, the *.ull file may be used as is and pulled into grammar learning.

**Comment by glicerico** [comment]
@akolonin A variation of the idea in this issue is what Sergey and Alexey Potapov are doing now, using their BERTRAM models. I would close this issue as it's description is outdated.

**Comment by akolonin** [comment]
Agreed

**Comment by akolonin** [comment]
I still think Ben's idea worth trying - we don't have reasonable alternatives better than "sequential parser" thus far.

**Comment by glicerico** [comment]
@akolonin , Ben's idea was refined by himself (after Potopov corrected Ben's idea that you copied in this issue), and that's what Potopov and Sergey are trying in their experiments GuChMI-v5, 6, 7.
