### ISSUE TITLE
Do we compare sentences with words ignored by Link-parser English?

### ISSUE THREAD

**Issue by glicerico** [singnet/language-learning#13]
We should discuss if sentences with [ignored] words by link-parser English are worth evaluating. 
After discussion with @alexei-gl , I think they are worth evaluating, to consider the links that are actually worth it, but then we need to shift the word order to account for ignored words. 
What I don't think is a good idea is to evaluate it without changing the word indexes.

**Comment by 98saurabh98** [comment]
Hi @glicerico, I am an undergrad student and want to start contributing to open source. Could you help me start to contribute? This may not be the right place to ask this, but I need help. I can definitely be of some use to you. Thanks.

**Comment by akolonin** [comment]
@glicerico - we need evaluate all links, as @alexei-gl suggested. And we need to have indexes calculated right. Also, we may want to have only one instance of evaluation code in the code base to minimise the effort doubling.

@98saurabh98 - this particular project is dedicated to computational linguistics and it is at early stage to have too many contributors. Still, if you are interested, please send your resume with your experiences, skills and taken courses, along with list of language that you speak and to which extent - send it to my email "akolonin at gmail dot com", please.

**Comment by glicerico** [comment]
@akolonin I agree to all your statements. @alexei-gl's evaluator is probably better code, but it needs to take care of the issues I submitted.

**Comment by glicerico** [comment]
I realized later that the indexes are actually handled properly. Of course this doesn't handle indexes for different tokenizations, but that's a different story
