### ISSUE TITLE
Make "ull" format of parses holding statistical information

### ISSUE THREAD

**Issue by akolonin** [singnet/language-learning#168]
It is needed for further account of statistical information associated with links (and/or) disjuncts known to MST-Parser so it could be potentially used by Grammar Learner when doing "probabilistic grammar induction", like taking more reliable links/disjuncts from the parses on earlier iterations and getting less and less reliable links/disjuncts during further iterations.
The "ull" format change requirement is the same as for #167
*Subtasks:*
1) Export MI (either corpus-bound or sentence-bound) when links are exported from OpenCog MST-Parser - as 5th positional argument on the every line corresponding to individual link 
2) Fix Grammar Learner so it 
2-a) does not break on new format 
2-b) consumes if for the later use (with unit test)
3) Fig Grammar Tester so it does not break on new format (with unit test)

**Comment by glicerico** [comment]
Submitted Pull Request https://github.com/singnet/opencog/pull/66 , which accomplishes subtask 1 above.

**Comment by akolonin** [comment]
Tasks 1 and 2 - done. @alexei-gl to do task 3 and have links to PR-s for 2 and 3 here

**Comment by akolonin** [comment]
@alexei-gl - can you finish your part of this task and hand it to @OlegBaskov on Monday?

**Comment by OlegBaskov** [comment]
Commit https://github.com/OlegBaskov/language-learning/commit/44ef579d6dae0f11f4c9a1fc71ed1ae20d42bcdb, PR https://github.com/singnet/language-learning/pull/190
