### ISSUE TITLE
Filter for testing corpus

### ISSUE THREAD

**Issue by akolonin** [singnet/language-learning#181]
Subtasks:
A) Create a filter that removes sentences that:
1) have different tokenization in LG English and the MST-parser
2) contain words that were not parsed by LG-English
3) contain dialogues or incomplete parts of dialogues inside them (e.g. "Not now" she said, "let's go tomorrow")
(@glicerico )

B) Run the http://langlearn.singularitynet.io/data/parses/English/Gutenberg-Children-Books/test/GCB-LG-English-clean.ull through this filter and create "gold standard GC parses" (@glicerico )

C) Integrate the filter as Grammar-Tester option (@alexei-gl )

**Comment by glicerico** [comment]
** A) Create a filter that REMOVES SENTENCES that:

**Comment by glicerico** [comment]
Tasks A) and C) are ready, just created pull request https://github.com/singnet/language-learning/pull/182

**Comment by glicerico** [comment]
@akolonin , for task B), this corpus is in a different order than the other ones I have created. Do you need that one in particular? If so, we need to sort the sentences somehow. If not, I have another one ready in the 88 server at /home/asuarez/parses/filtered_parses_win6_omdist.ull

**Comment by akolonin** [comment]
@glicerico - what was the source of your http://langlearn.singularitynet.io/data/andres_parses/filtered_parses_win6_omdist.ull ?
Why is it called "...win6_omdist..." - have you used MST-Parses to create it?

For B) and for linguist, we need filter applied to  http://langlearn.singularitynet.io/data/parses/English/Gutenberg-Children-Books/test/GCB-LG-English-clean.ul - this is list of sentences that are 100% parsed by LG-English grammar, that would give us "gold standard"

**Comment by glicerico** [comment]
@akolonin the way the filter works is that it compares two files, and finds the sentences that are tokenized differently, and the ones that have internal quotes, just like I mentioned in the A) above that describes this issue... so the uploaded file is called like that because it's comparing the LG parse file to the win6_omdist file, but the parses that are printed there are actually the LG parses... perhaps we could set a better name for it.

> this is list of sentences that are 100% parsed by LG-English grammar (filtered by Oleg earlier), that would give us "gold standard"
This is done by the newly created filter also, because if a sentences was not parsed completly by LG-English, then some words appear between brackets, and the filter will realize it's not the same as the one in the mst-parsed file... so this answers my question: we don't need to use the file that you are referencing.

however, it would be good to get a file parsed with the latest link-parser, and then I can filter that one.

**Comment by akolonin** [comment]
@glicerico - are you saying the "...win6_omdist..." is subset of GCB-LG-English-clean.ull with different sorting? If so, is it a big deal to re-run the filter so the order is taken from the latter file and saved to GCB-LG-English-clean-gold.ull to have the B) done? And what file it was compared to?

**Comment by glicerico** [comment]
@akolonin Exactly, it's a subset in a different order.
I'm not sure which order do you want to preserve, but I need to have one file with LG-parses and one file with MST-parses to be able to filter the LG-parse file (to catch every different tokenization). With those requisites, running the filter is a matter of a few minutes.
Note: the current LG-parse file that I have is not the latest one. Can you or @alexei-gl tell me where to find the latest version LG-English parses for GC?

**Comment by akolonin** [comment]
@glicerico - I understand.
Can you re-run the filter so the order is taken from the GCB-LG-English-clean.ull file and results are saved to GCB-LG-English-clean-gold.ull

On your question on LG version. We can do that later, otherwise we need to redo the effort to create GCB-LG-English-clean.ull - that will be not trivial. Version of LG does not matter now because parses for gold standard are going to get fixed manually anyway.

**Comment by glicerico** [comment]
@akolonin , no... I can't run the filter on GCB-LG-English-clean.ull because I don't have an MST parsed file in that order. Why do you need that order specifically?
OK about the LG version

**Comment by akolonin** [comment]
@glicerico - I am looking into http://langlearn.singularitynet.io/data/parses/English/Gutenberg-Children-Books/LG/capital/11-0.txt.ull and I am not seeing parse "presently she began again ." in http://langlearn.singularitynet.io/data/andres_parses/filtered_parses_win6_omdist.ull 
while having http://langlearn.singularitynet.io/data/parses/English/Gutenberg-Children-Books/GC_lgAll/parses/11-0.txt_headless_split_default.ull

**Comment by akolonin** [comment]
Another real problem that I see is lots of

**Comment by glicerico** [comment]
> Should we consider fixing MST-Parser or Pre-Cleaner to handle period properly instead of eliminating all sentences that end with period?

@akolonin , I thought I had commented about this last time, but maybe I forgot. This is an inconsistency in the mst-parser writer, where the sentence is printed as it is before final tokenization. See in the mst-parsed file how the final dot is not separated, but then the links do consider it as a separate token:

>presently she began again.
>0 ###LEFT-WALL### 1 presently
>1 presently 3 began
>1 presently 2 she
>3 began 4 again
>4 again 5 .

This should be easy to fix in the MST-parser side, and then I need to re-run this MST-parses to re-generate the filtered sentences for the linguist.
Thanks for keeping an eye, and please report any other findings.

**Comment by glicerico** [comment]
@akolonin The specification was to remove dialogues inside the sentence. I interpreted it as sentences that mix dialogue and narration, like `"Taste this", she said, "you'll love it"`
The examples that you mention:

> is lots of double quotes like: which of us will you marry , Phillippa ? "

are actually parts of a dialogue, but they don't get interrupted by a narrator, so I didn't remove it on purpose, so it's design, not a bug. 
If we want to remove anything that contains dialogue quotes I can do that, but I'm not sure that's what we want. Is it?

**Comment by akolonin** [comment]
@glicerico - I suggest to 1) remove any sentences with quotes (may be configuration option), 2) get back sentences ending with period.

Having this issue in MST-Observer and MST-Parser is an issue on itself, because your parses won't be matching LG-Parses. I now wonder if the tokenization of the period in MI-Observer and MST-Parser is different or not. If it is only just the **writing issue**, then yes, I think it has to be fixed otherwise things would go crazy on pipeline further.

**Comment by glicerico** [comment]
@akolonin, I was able to create the file that you wanted in order, because now MST-parses will imitate the LG-English tokenization, and also removed all quotes. You can find it in: http://langlearn.singularitynet.io/data/andres_parses/GC_LGEnglish_noQuotes_fullyParsed.ull

**Comment by akolonin** [comment]
@glicerico - look good but I have one more question for you ad @alexei-gl - why do we have 

you don't , you say , like this cruise .
0 ###LEFT-WALL### 1 you
0 ###LEFT-WALL### 7 like
0 ###LEFT-WALL### 10 .
1 you 2 don't
2 don't 7 like
3 , 5 say
4 you 5 say
5 say 6 ,
5 say 7 like
7 like 9 cruise
8 this 9 cruise

and

that was the ship 's mystery .
0 ###LEFT-WALL### 1 that
0 ###LEFT-WALL### 2 was
0 ###LEFT-WALL### 7 .
1 that 2 was
2 was 6 mystery
3 the 4 ship
4 ship 5 's
5 's 6 mystery

So why some of the words are torn apart on the apostrophe and some are not?

**Comment by akolonin** [comment]
@glicerico + @alexei-gl , here is what I see in the cleaned corpus

akolonin@Ubuntu-1604-xenial-64-minimal:~/public/cleaned/English/Gutenberg-Children-Books/lower$ grep cruise * | grep don
...
pg120.txt:you don't , you say , like this cruise.
...
akolonin@Ubuntu-1604-xenial-64-minimal:~/public/cleaned/English/Gutenberg-Children-Books/lower$ grep mystery * | grep ship 
...
pg120.txt:that was the ship's mystery.

That means, pre-cleaner works just fine, but LG-English parser disassembles some words and does not disassemble the others. Why?

**Comment by glicerico** [comment]
That's the way the LG English tokenizer works, which we will follow to compare more properly.
It doesn't in general split negation contractions, I believe it considers don't as a new verb (negated do). In the case of 's it is either a particle about belonging or a verb (in the verb case, it considers it as synonym to is).

**Comment by akolonin** [comment]
@glicerico - great work, in general, passing the file to further now :-)

**Comment by akolonin** [comment]
> it considers it as synonym to is
Andres, accordingly to this logic, "don't" should be "tokenized" as "do" and "n't", right? 
All that said, as long as we don't support unsupervised morphology learning in ULL, as Linas would mean in the earlier reply, we should not not be considering pieces of "ship's" in the "gold standard", right?

**Comment by glicerico** [comment]
I would think that our methods should be able to handle this particles (e.g. " 's "), and as long as they're tokenized same as our standard (which they are now), I think we should leave them.

**Comment by akolonin** [comment]
akolonin@Ubuntu-1604-xenial-64-minimal:~/public/parses/English/Gutenberg-Children-Books/GC_lgAll/parses$ grep ship pg120.txt_headless_split_default.ull | grep mystery
that was the ship's mystery.
4 ship's 5 mystery

@glicerico - we can't handle them in MST-parses, right? See above. To handle them properly, you should have LG-English parsing process instead of plain tokenization in pre-cleaner. That won't be quite ULL. And since we can't evaluate them in MI-Observer and MST-Parser, correctly (until we support morphology learning), we should not have them in "gold standard". My next question is if DNN-MI is being trained on disassembled "ship's" or not.

**Comment by akolonin** [comment]
@glicerico - I see that you have them disassembled already:
http://langlearn.singularitynet.io/data/cleaned/English/Gutenberg-Children-Books/lower_LGEng_token/pg120.txt_headless_split_U.ull
:-)
So do you want to regenerate all MST-Parses based on that now? If so, we would have a fresh start for GC based on that, and redo all sequential and random and all sorts of MST-Parses based on that LG-English tokenized corpus, is it what you suggest?

**Comment by glicerico** [comment]
@akolonin , you're right, when we remove the tokenization from the ULL pipeline, we need to do it in some other way and in this case we're copying the tokenization from LG-English. About "supervision", pre-cleaning is also supervision... so until we have a proper unsupervised tokenizer, I don't see the difference if we use LG-English tokenizer. Please see my email response to Linas in lang-learn forum, and tell me if you agree or not :)
https://groups.google.com/forum/#!msg/lang-learn/-Knw1UDC4TQ/3ZFhAjk1BwAJ

**Comment by akolonin** [comment]
@glicerico - I disagree strategically but I agree tactically :-D
But then you have to agree to regenerate all baseline parses based on new "LG-english-clean" corpus ;-)
If you agree, let's close this and discuss the rest on Monday.
