### ISSUE TITLE
Grammar Tester selectivity configuration

### ISSUE THREAD

**Issue by akolonin** [singnet/language-learning#184]
We need to have Grammar Tester being able to skip sentences on base of few criteria, so the skipped sentences are not counted in statistics (with extra statistics for "Skipped by filter sentences" added). 
This extends work on #181 . 
Subtasks:
1. Configure GT with list "stop_tokens" of tokens, so that appearance of any token in the test sentence in a sentence would skip the sentence. Default - empty list.
2. Configure GT with minimum number "minimum_word_count" of word occurrences in a test corpus so appearance of any word with number of occurrences below the threshold would skip the sentence. The GT may have to read entire input test corpus to count statistics before actual testing for that. Default - 0 which means no skips.
3. Configure GT with maximum number "maximum_sentence_length" of words in a test sentence so any sentence with greater number of words would get skipped. Default - 0 which means no limit.
4. During the GT process, output only the parses that are actually test.
5. Provide unit tests for the above.
6. Test GC ILE-generated grammar with the following configurations
minimum_word_count=0, maximum_sentence_length=0
minimum_word_count=5, maximum_sentence_length=0
minimum_word_count=10, maximum_sentence_length=0
minimum_word_count=50, maximum_sentence_length=0
minimum_word_count=0, maximum_sentence_length=5
minimum_word_count=0, maximum_sentence_length=10
minimum_word_count=0, maximum_sentence_length=15
minimum_word_count=0, maximum_sentence_length=25

**Comment by alexei-gl** [comment]
```
MWC(GT) MSL(GT) PA F1
0       0       61.69%       0.65
5       0       100.00%       0.40
10      0      100.00%       0.40
50      0      100.00%       0.41
0       5       70.06%       0.25
0       10     66.60%       0.29
0       15     63.87%       0.29
0       25     61.69%       0.65
```

**Comment by alexei-gl** [comment]
The latest results for CDS:
http://langlearn.singularitynet.io/data/aglushchenko_parses/CDS-dILEd-MWC-MSL-2019-04-13/
The latest results for restricted GC corpus with no direct speech can be found here:
http://langlearn.singularitynet.io/data/aglushchenko_parses/GCB-NQ-dILEd-MWC-MSL-2019-04-13/

**Comment by alexei-gl** [comment]
Results update:
```
MWC(GT) MSL(GT) PA      F1
0       0        61.69%   0.65
1       0        61.69%   0.65
2       0       100.00%   1.00
3       0       100.00%   1.00
4       0       100.00%   1.00
5       0       100.00%   1.00
10      0       100.00%   1.00
50      0       100.00%   1.00
0       2        99.60%   1.00
0       3        79.41%   0.79
0       4        71.95%   0.73
0       5        70.06%   0.72
0       10       66.60%   0.69
0       15       63.87%   0.67
0       25       61.69%   0.65
```
http://langlearn.singularitynet.io/data/aglushchenko_parses/GCB-NQ-dILEd-MWC-MSL-2019-04-24/
