### ISSUE TITLE
Integrate two different parse evaluators

### ISSUE THREAD

**Issue by glicerico** [singnet/language-learning#186]
We currently have two versions of the parse evaluator (contained in https://github.com/singnet/language-learning/blob/master/src/parse_evaluator/parse_evaluator.py and https://github.com/singnet/language-learning/blob/master/src/grammar_tester/parsevaluate.py). 
As @alexei-gl  suggested, we should integrate them at some point, to avoid any possible difference in their estimates.

**Comment by alexei-gl** [comment]
@glicerico , I just made PR with updated parse-evaluator. I decided to keep alternative mode until it is clear that ordinary mode is bug free.Please, check when you have time.
