### ISSUE TITLE
Test reproduceability of results for GC with LG 5.5.1

### ISSUE THREAD

**Issue by akolonin** [singnet/language-learning#196]
They are not reproducible now:
comparing
http://langlearn.singularitynet.io/data/clustering_2019/ALE50-GCB-LG-E-noQuotes-2019-03-27/all_tests_table.txt
against
http://langlearn.singularitynet.io/data/clustering_2019/html/ALE-GCB-LG-E-noQuotes-MWC=6-2019-03-26.html
and
http://langlearn.singularitynet.io/data/clustering_2019/html/ALE-GCB-LG-E-noQuotes-MWC=1-2019-03-26.html

**Comment by OlegBaskov** [comment]
Tests for the [Gutenberg-Children (train/test with 100% LG Parses with no quotes 5.5.1)](https://docs.google.com/spreadsheets/d/1TPbtGrqZ7saUHhOIi5yYmQ9c-cvVlAGqY14ATMPVCq4/edit#gid=963717716&range=L46:U51] checked on a fresh clone of the `singnet/language-learning` repository, fresh `ull` envitonment created from `environment.yml` pulled from the repo (dated 2018-03-18): 
[ALE50](http://langlearn.singularitynet.io/data/clustering_2019/cALEd-50-GCB-LG-E-noQuotes-2019-04-03/all_tests_table.txt), [ALE500](http://langlearn.singularitynet.io/data/clustering_2019/html/cALEd-500-GCB-LG-E-noQuotes-S94-2019-04-02.html), [ALE1000](http://langlearn.singularitynet.io/data/clustering_2019/cALEd-1000-GCB-LG-E-noQuotes-2019-04-03/all_tests_table.txt), [ALE2000](http://langlearn.singularitynet.io/data/clustering_2019/cALEd-2000-GCB-LG-E-noQuotes-2019-04-03/all_tests_table.txt), [dILEd](http://langlearn.singularitynet.io/data/clustering_2019/ILE-GCB-LG-E-noQuotes-LG_551-S94-2019-04-02/all_tests_table.txt).  
Results of the previous 2019-03-25 tests reprocuced.
