### ISSUE TITLE
GL exception 'list index out of range'

### ISSUE THREAD

**Issue by alexei-gl** [singnet/language-learning#209]
Grammar learner fail with exception IndexError 'list index out of range'  on corpus http://langlearn.singularitynet.io/data/parses/English/Gutenberg-Children-Books/LG5.5.1/capital/sequential_parses.ull when started with the following settings:
```
    "component": "grammar-learner",
    "common-parameters": {
        "left_wall":            "",
        "period":               false,
        "min_word_count":       1,
        "grammar_rules": 2,
        "clustering_metric":    ["silhouette", "cosine"],
        "max_disjuncts":        1000000,
        "stop_words":           [],
        "top_level":            0.01
    },
    "specific-parameters": [
      { "context": 1, "word_space": "sparse",   "clustering": ["aglomerative", "ward"], "cluster_range": [500]}
    ]
  },
```

**Comment by akolonin** [comment]
See: https://github.com/OlegBaskov/language-learning/issues/107

**Comment by OlegBaskov** [comment]
Could not reproduce the error in [Jupyter notebook](http://langlearn.singularitynet.io/data/clustering_2019/html/issue_209_cALEd-500-GCB-sequential_parses-MWC=1-2019-04-24_.html).  
How exactly should I run the pipeline developed by @alexei-gl to get the error?

**Comment by alexei-gl** [comment]
@OlegBaskov , please postpond it for a little while. I have to rerun it with the updated code.

**Comment by alexei-gl** [comment]
@OlegBaskov , I managed to reproduce the bug on smaller corpus. You can find it at the end of the log file here: http://langlearn.singularitynet.io/data/aglushchenko_parses/CDS-ALE-ILE-TEST-2019-04-25/CDS-ALE-ILE-TEST.log .
To reproduce the bug simply copy the folder: http://langlearn.singularitynet.io/data/aglushchenko_parses/CDS-ALE-ILE-TEST-2019-04-25 to any location in your profile on the server and from within the folder run:
```
source activate ull
ull-cli -C CDS-ALE-ILE-TEST.json --logging=debug
```

**Comment by OlegBaskov** [comment]
I have fixed agglomerative clustering to return single-word clusters when requested number of clusters more than number of unique words in the training set (in your case: 400 clusters for the "Child Directed speech LG-E-clean" dataset, containing 301 unique words -- [issue_209_CDS-ALE_ILE-LG-English-clean-2019-04-25.html](http://langlearn.singularitynet.io/data/clustering_2019/html/issue_209_CDS-ALE_ILE-LG-English-clean-2019-04-25.html).  
However, I could not make `ull-cli -C CDS-ALE-ILE-TEST.json --logging=debug` work: 
```
(ull) 88 $ cd ~/CDS-ALE-ILE-TEST-2019-04-25
(ull) 88 $ ull-cli -C CDS-ALE-ILE-TEST.json --logging=debug
ull-cli ver.1.0.0
Python v.3.6.6
ull-cli ver.1.0.0
Python v.3.6.6
Virtual environment: ull
grammar-tester(cfg=1, run=1):TypeError:'>' not supported between instances of 'str' and 'int'
Traceback (most recent call last):
  File "/home/obaskov/anaconda3/envs/ull/lib/python3.6/site-packages/ull/pipeline/pipelinetreenode.py", line 69, in traverse
    job(node)
  File "/home/obaskov/anaconda3/envs/ull/lib/python3.6/site-packages/ull/pipeline/pipelinetree.py", line 155, in single_proc_exec
    result = component.run(**{**parameters, **result})
  File "/home/obaskov/anaconda3/envs/ull/lib/python3.6/site-packages/ull/grammar_tester/grammartester.py", line 464, in run
    options, TextProgress, **kwargs)
  File "/home/obaskov/anaconda3/envs/ull/lib/python3.6/site-packages/ull/grammar_tester/grammartester.py", line 289, in test
    if self._test_kwargs.get("min_word_count", 0) > 1:
TypeError: '>' not supported between instances of 'str' and 'int'
```
I have made fresh clones of singnet/language-learning repository on both servers, tried to reinstall opencog-ull after my updates -- results are the same.
