### ISSUE TITLE
parse-evaluator should be able to compare parses with inconsistent tokenization

### ISSUE THREAD

**Issue by akolonin** [singnet/language-learning#226]
Based on the following discussion with @glicerico , need to make it possible for parse-evaluator to compare parses with inconsistent tokenization like it was possible before the latest refactoring. 

1. Ideally, provide the option to either A) verify the words and sentence strictly (like it does now) OR B) report the differences as warnings and ignore/skip them during comparison reporting the number of skipped sentences in statistics, but still fail if number of sentences mismatch

2. To make sure it is fixed, fill the cell I64 in "Parses" sheet for http://langlearn.singularitynet.io/data/parses/English/Gutenberg-Children-Books/GC_psg/parses/

3. Any errors failing the execution **must** report name of the failing file and _should_ report the line number. 

------------------------
Anton Kolonin [12:16 PM]
Looking into cell I63: http://langlearn.singularitynet.io/data/parses/English/Gutenberg-Children-Books/BERTRAM-weights-parses/GuChMI-v4-sumabs-parses/parses/pg24875.ull (edited) 
There is a computed F1=0.52 (edited) 
There is no period in the parses:
" well , of all wonderful things ! " commented mrs stapp .
So how the number F1=0.52 was computed if the reference has the period? http://langlearn.singularitynet.io/data/parses/English/Gutenberg-Children-Books/LG5.5.1/capital/parses/pg24875.txt.ull
" well , of all wonderful things ! " commented [Mrs] . Stapp .

Anton Kolonin [12:31 PM]
Here is another glithch:
http://langlearn.singularitynet.io/data/parses/English/Gutenberg-Children-Books/BERTRAM-weights-parses/GuChMI-v4-sumabs-parses/parses/pg36532.ull
page @number@ principle amended to principal " ....y but the cat lay down outside the principal gate , ....v "
http://langlearn.singularitynet.io/data/parses/English/Gutenberg-Children-Books/LG5.5.1/capital/parses/pg36532.txt.ull
page @number@ principle amended to principal " ....v but the cat lay down outside the principal gate , ....n "

Andres Suarez [12:32 PM]
ok, i looked a bit into this. The situation is this:
- If you remember, there was a slight difference between parses LG5.5.1 and oldLG ones
- I think I remember that the dot disappearance was noted by me before as a difference, and I noted it down in my notebook, but that notebook has been already been replaced and I don't have it with me right now. Still, the differences in the tokenization (this applies as that) were not large.
- The http://langlearn.singularitynet.io/data/cleaned/English/Gutenberg-Children-Books/lower_LGEng_token files were created using the oldLG, thus are missing a dot.
- My "alternative" parser was able to compare sentences with different tokenization
- The new parser that @alex finished recently (good work!) is more restrictive and warns or stops if there is tokenization difference, that's why @anton is not able to evaluate

Anton Kolonin [12:32 PM]
How you were able to compare the parses at all?

Andres Suarez [12:33 PM]
> Here is another glithch:
What's the difference in this one?

Anton Kolonin [12:33 PM]
Ok, at least I am not crazy :slightly_smiling_face:
> - My "alternative" parser was able to compare sentences with different tokenization
What was your action on discrepances? Skipping the sentences?
> What's the difference in this one?
Don't you see the letters?

Andres Suarez [12:34 PM]
the tags for the dots??
"....y " vs "....v "?
>What was your action on discrepances? Skipping the sentences?
No, still evaluating... this problem of tokenization discrepancy has been long known and reported. Even in my thesis
> "....y " vs "....v "?
My evaluator doesn't care about the letter difference, it still evaluates based on the position of the words

Anton Kolonin [12:40 PM]
I know about tokenization issue, I just want to:
1) know what you was doing on discrepances so @alex can put this feature back so we are not stuck on this
2) learn what is the origin of these y and v - are these coming from tokenization? (edited) 

Andres Suarez [12:41 PM]
the punctuation mark "..." is tagged differently by different LG grammar versions: ".v" in one case, ".y" in another case (edited) 
this was also known
> 1) know what you was doing on discrepances so @alex can put this feature back so we are not stuck on this
I just didn't compare the sentences. That's why the sentence order is super important in the alternative tokenizer (as well as in the new one)

Anton Kolonin [12:44 PM]
@asuarez thanks, @alex please put this option back ASAP so we can keep working (you can make this as CLI option with either on or off by default, whatever is easier) and let me know.

Andres Suarez [12:45 PM]
i would like to know @alex opinion on this before deciding. What's advantages do you see in making the parse-evaluator so strict?

Anton Kolonin [12:45 PM]
I am fine with strictness option, so we can catch the differences in tokenization rather soon.
However, we knew this problem for this GC round and we need to complete this round being aware of the problem and ignoring the differences which are known to be few. (edited) 

Andres Suarez [1:18 PM]
> please put this option back ASAP so we can keep working
@anton, you can still use the -a option to activate the alternative parser, by the way... then you won't be stopped

Anton Kolonin [1:20 PM]
$ parse-evaluator -r gc_full_lge_hacked -t gc_full_ull -i -a
<class 'IsADirectoryError'>: [Errno 21] Is a directory: 'gc_full_lge_hacked'
Traceback (most recent call last):
 File "/home/akolonin/miniconda3/envs/ull/bin/parse-evaluator", line 147, in main
   compare_tokenization, **params)
 File "/home/akolonin/miniconda3/envs/ull/lib/python3.6/site-packages/ull/parse_evaluator/parse_evaluator.py", line 264, in Evaluate_Alternative
   ref_data = Load_File(ref_file)
 File "/home/akolonin/miniconda3/envs/ull/lib/python3.6/site-packages/ull/parse_evaluator/parse_evaluator.py", line 15, in Load_File
   with open(filename) as file:
IsADirectoryError: [Errno 21] Is a directory: 'gc_full_lge_hacked'
(ull) akolonin@Ubuntu-1604-xenial-64-minimal:~/test/syntgrams$ parse-evaluator -r gc_full_lge_hacked -t gc_full_ull -i -a
@asuarez the alternative parser does not handle directories?

Andres Suarez [1:21 PM]
ah, yes... alternative parser doesnt...
exactly

Anton Kolonin [1:21 PM]
ok, so I wait :slightly_smiling_face:

Andres Suarez [1:21 PM]
but it's easy... just
cat your_dir/* > all_parses.ull
then you can compare the files

Anton Kolonin [1:22 PM]
Ok, if @alex won't fix that by tomorow morning :wink:

Andres Suarez [1:22 PM]
ok

Anton Kolonin [2:10 PM]
@alex - to make sure it is fixed, please fill the cell I64 for http://langlearn.singularitynet.io/data/parses/English/Gutenberg-Children-Books/GC_psg/parses/

**Comment by alexei-gl** [comment]
PR #227 has added new options to parse-evaluator:
        -T              strict tokenization (forces PE to treat tokenization discrepancies as errors)
        -S              ignore sentences mismatch (forces PE to carry on evaluation even if sentences mismatch)
The table cell filled with value.
