### ISSUE TITLE
Cleanup GL/GT output structure

### ISSUE THREAD

**Issue by akolonin** [singnet/language-learning#229]
1. Currently, output folder is mess up of parse files with statistics and grammar
http://langlearn.singularitynet.io/data/aglushchenko_parses/GCB-FULL-ANY-ALE500-2019-05-08-94/parses/ 
- it makes no sense and should be cleaned up

2. Not clear why we need two dict files in the tree
http://langlearn.singularitynet.io/data/aglushchenko_parses/GCB-FULL-ANY-ALE500-2019-05-08-94/
in
http://langlearn.singularitynet.io/data/aglushchenko_parses/GCB-FULL-ANY-ALE500-2019-05-08-94/GL_context:1_db-row:1_f1-col:8_pa-col:3_word-space:sparse/
and in
http://langlearn.singularitynet.io/data/aglushchenko_parses/GCB-FULL-ANY-ALE500-2019-05-08-94/parses/ 

3. Not clear why we need duplicated re in the folder structure
http://langlearn.singularitynet.io/data/aglushchenko_parses/GCB-FULL-ANY-ALE500-2019-05-08-94/ref/

**Comment by alexei-gl** [comment]
1. It is rather configuration issue, not a bug. 
2. Single configuration had been intrrupted after GL complete for some reason and then GT was restarted separately with different .json configuration file. A copy of `GL_context:1_db-row:1_f1-col:8_pa-col:3_word-space:sparse` was called `parses` to avoid long folder name in GT .json configuration file.
3. 'ref' is a symbolic link created for the readability in .json file and easy data management.
