### ISSUE TITLE
Number of sentences does not match. Read: 457, Parsed: 229, File: ...English_noQuotes_manual.ull

### ISSUE THREAD

**Issue by alexei-gl** [singnet/language-learning#231]
GL failes with an exception "ull.grammar_tester.lgmisc.LGParseError: Number of sentences does not match. Read: 457, Parsed: 229, File: ...English_noQuotes_manual.ull".

**Comment by alexei-gl** [comment]
As it turned out corpus file `/home/akolonin/public/parses/English/Gutenberg-Children-Books/test/GC_LGEnglish_noQuotes_manual.ull` has Windows style CR/LF:
```
00000000  74 68 65 20 6f 6c 64 20  62 65 61 73 74 20 77 61  |the old beast wa|
00000010  73 20 77 68 69 6e 6e 79  69 6e 67 20 6f 6e 20 68  |s whinnying on h|
00000020  69 73 20 73 68 6f 75 6c  64 65 72 20 2e 0d 0a 0d  |is shoulder ....|
00000030  0a 4a 69 6d 73 20 6c 69  66 74 65 64 20 68 69 73  |.Jims lifted his|
00000040  20 6d 69 73 65 72 61 62  6c 65 20 65 79 65 73 20  | miserable eyes |
00000050  2e 0d 0a 0d 0a 46 61 69  74 68 20 63 61 72 72 69  |.....Faith carri|
00000060  65 64 20 61 20 68 65 61  76 79 20 68 65 61 72 74  |ed a heavy heart|
00000070  20 74 6f 20 62 65 64 20  77 69 74 68 20 68 65 72  | to bed with her|
00000080  20 74 68 61 74 20 6e 69  67 68 74 20 2e 0d 0a     | that night ...|
0000008f
```
On one hand the CR/LF problem causes improper sentence counting. On the other hand `0a` in input stream makes `link-parser` return two linkages instead of one (not sure if it is a bug or feature of `link-parser`).

**Comment by akolonin** [comment]
@alexei-gl - can you fix and overwrite the files?

@glicerico - which part of the code should be causing this - can it be fixed?

**Comment by glicerico** [comment]
This must be caused by the linguist creating/editing the parses in Windows. A simple converter would fix it, like dos2unix

**Comment by alexei-gl** [comment]
PR #233 fixes the issue.
