### ISSUE TITLE
grammar-tester lg_dict version bug

### ISSUE THREAD

**Issue by glicerico** [singnet/language-learning#242]
The way grammar tester reports version has a bug: if there's a comment talking about "UNKOWN-WORD" without brackets "<>" before the first rule for "<UNKNOWN-WORD>", reported version will be 5.4.0.

Example: LG-English dict file v5.5.1 has the following (line 12686):
% by the UNKNOWN-WORD.a rule -- "Umm, I think he did it."

**Comment by alexei-gl** [comment]
Fixed in PR #250
