### ISSUE TITLE
Make pearson_coeff consistent to Python styling and ULL code structure

### ISSUE THREAD

**Issue by akolonin** [singnet/language-learning#55]
Please rename 
https://github.com/singnet/language-learning/blob/master/src/PearsonCoeff/PearsonsCoeff.py
to pearson_coeff.py and move it to 
https://github.com/singnet/language-learning/tree/master/src/common
then delete 
https://github.com/singnet/language-learning/tree/master/src/PearsonCoeff
- for naming consistency.

**Comment by glicerico** [comment]
Fixed in https://github.com/singnet/language-learning/pull/63
